"use client";

import {
  LegalDocumentLayout,
  type LegalSection,
} from "@/components/legal/LegalDocumentLayout";
import {
  COMPANY_ADDRESS,
  COMPANY_NAME,
  EFFECTIVE_DATE,
  LAST_UPDATED,
  LEGAL_EMAIL,
  PRIVACY_EMAIL,
} from "@/lib/legal-constants";

const sections: LegalSection[] = [
  {
    title: "Scope and Roles",
    content: [
      `${COMPANY_NAME} ("Pholio," "we," "us," or "our") operates a service through which an individual Talent user, or an authorized parent or guardian for a minor, can prepare and send materials to an identified Recipient.`,
      `"Recipient" can mean a talent or modeling agency, model management company, casting organization, event producer, fashion-week organizer, brand, client, or other organization identified for the particular submission. "Talent" means the person whose profile and materials are submitted.`,
      `Pholio controls the Platform account, technical transmission, and consent or audit records described here. A Recipient that determines its own evaluation, retention, selection, work, or publicity purposes is an independent controller or business for that activity unless an opportunity-specific notice says otherwise.`,
      `This Notice supplements the Privacy Policy, Terms of Service, AI Notice, Community and Safety Guidelines, and the specific opportunity details shown to Talent.`,
    ],
  },
  {
    title: "Representation Submissions and Opportunity Submissions",
    content: [
      `2a. Agency representation\nAn agency submission asks an identified agency to consider Talent for possible representation, a meeting, or a later discussion. It does not create representation or require a response.`,
      `2b. Casting, event, brand, or client opportunity\nAn opportunity submission asks the identified Recipient to consider Talent for the event, runway, casting, campaign, project, or other purpose stated for that opportunity. It is not an agency-representation request unless expressly identified as one.`,
      `2c. Opportunity details\nBefore submitting, review the Recipient's identity and role, opportunity or event, location and dates if known, eligibility, deadline, compensation or unpaid status if known, expenses, selection process, decision-maker, data fields, AI or ranking use, retention, publicity or usage request, withdrawal method, accessibility contact, and additional terms. If those facts are missing or unclear, contact ${LEGAL_EMAIL} before submitting.`,
      `2d. Correct recipient\nDo not submit if the displayed Recipient, purpose, or opportunity is not the one you intend. Pholio cannot treat an event producer as an agency or transform a representation application into consent for event participation.`,
    ],
  },
  {
    title: "Data Included in a Submission",
    content: [
      `A submission can include the following categories to the extent selected, required, available in the account, generated by the Platform, or stated for the opportunity:`,
      `3a. Identity and contact data\nName, professional name, pronouns, date of birth or age band, city, state, country, market, email, telephone number, portfolio URL, and social-media links.`,
      `3b. Professional data\nBiography, languages, training, experience, credits, specialties, categories, booking lanes, representation information, work-eligibility information, union status, availability, and other professional details.`,
      `3c. Measurements and appearance data\nHeight, weight, bust or chest, waist, hips, inseam, dress, suit and shoe measurements, hair and eye color, gender or division information, body type, tattoos, piercings, ethnicity or heritage, and similar information.`,
      `3d. Images and media\nHeadshots, full-length images, digitals, book or editorial images, comp-card images, file and image metadata, image order, shot type, recency, and rights or release information.`,
      `3e. Application and communication data\nRecipient, opportunity or board, package configuration and fingerprint, selected materials, note, dates, status, messages, interview information, withdrawal, and Recipient activity within Pholio.`,
      `3f. Derived, consent, and technical data\nProfile completeness, quality or compatibility information, AI descriptions, embeddings or ranking data where used, subscription or quota status, disclosure and authorization records, guardian information, self-reported permit status, IP address, user agent, approximate location, timestamps, and audit events.`,
    ],
  },
  {
    title: "Sensitive Data, AI, and Ranking",
    content: [
      `Measurements, ethnicity or heritage, age, gender information, images, and appearance descriptors can be sensitive in context and can reveal or correlate with protected characteristics. Provide only information reasonably necessary for the stated purpose.`,
      `Pholio may use automated systems for completeness, image analysis, embeddings, semantic search, compatibility, quality, ranking, or sorting. Depending on the feature, inputs can include profile text, images, location, age band, gender or division information, measurements, body type, ethnicity or heritage, and Recipient criteria. See the AI Notice.`,
      `Image analysis and profile embeddings are separate processing activities. An image-setting choice does not necessarily disable embeddings or historical outputs. An opportunity-specific notice may state that automated ranking is disabled.`,
      `A Recipient remains responsible for human review and for any bias audit, candidate notice, alternative process, accommodation, discrimination, or automated-decision obligation. Talent may contact ${PRIVACY_EMAIL} to object to qualifying profiling or request human review.`,
    ],
  },
  {
    title: "Transmission and Recipient Access",
    content: [
      `Talent directs Pholio to transmit the selected package to the identified Recipient. Authorized Recipient personnel can include owners, agents, bookers, scouts, casting staff, event personnel, client personnel, or administrators with a legitimate role for the stated purpose.`,
      `The Recipient may view, print, export, download, or internally share submitted materials as reasonably necessary for evaluation and administration, subject to its agreement with Pholio and applicable law. A later profile or media update can affect current information displayed alongside the historical application.`,
      `The submission itself is not a public application. It does not automatically change separate public-portfolio or discoverability settings. Information already public or discoverable remains available independently of the submission.`,
      `A Recipient can retain an independent copy. Pholio can restrict future in-product access but cannot recall every print, download, screenshot, cache, communication, or external record.`,
    ],
  },
  {
    title: "No Relationship, Guarantee, or Authority",
    content: [
      `A submission does not create representation, management, employment, independent-contractor, fiduciary, partnership, joint-venture, confidential, booking, client, or other legal relationship. Any later relationship requires a separate agreement between the relevant parties.`,
      `As part of the standard Platform transmission service, Pholio does not sign for Talent, negotiate compensation or commissions on Talent's behalf, issue a work permit, establish immigration status, or accept an engagement for Talent.`,
      `No submission guarantees review, response, interview, meeting, representation, selection, booking, engagement, work, permit, travel, compensation, or income. A Platform score, status, invitation, or Recipient listing is not a professional license, background check, government approval, or safety guarantee.`,
    ],
  },
  {
    title: "Fees, Subscriptions, and Selection",
    content: [
      `A Pholio subscription is payment for software features, not payment to the Recipient, a commission, a success fee, or payment to secure selection.`,
      `A free or paid plan can have different Platform quotas, presentation tools, or routing features if those differences are disclosed in the product or checkout. Those differences do not guarantee review or an outcome.`,
      `An opportunity-specific rule may require that participation be free and that subscription status, paid routing, ranking, or visibility not affect eligibility or selection. The opportunity-specific rule controls.`,
      `Do not pay a Recipient or third party for guaranteed selection, work, immigration status, or earnings. Report a deceptive payment demand to ${LEGAL_EMAIL}.`,
    ],
  },
  {
    title: "Minors and Work Authorization",
    content: [
      `Users under 13 may not create a Pholio account or submit materials. A user aged 13 to 17 requires guardian knowledge, supervision, and authorization and remains subject to any higher minimum age set for the opportunity.`,
      `A guardian email, consent link, or account record is not proof of the guardian's identity, adulthood, relationship, custody, or legal authority. Pholio may request additional evidence or restrict a profile or submission.`,
      `Guardian authorization to transmit a package is not consent to employment, independent-contractor work, travel, fitting, test shoot, medical examination, nudity, publicity, merchandising, digital-replica use, power of attorney, or a representation agreement.`,
      `Child-performer permits, employer certificates, advance notice, school and work-hour limits, trust accounts, responsible adults, chaperones, safety measures, insurance, and other requirements may apply before work. A self-reported "work permit on file" indicator is not verification and does not satisfy a Recipient's duties.`,
      `Known minors may have separate consent rights for nonessential processing. A guardian authorization does not replace the minor's own choice where applicable law gives that choice to the minor.`,
    ],
  },
  {
    title: "Work, Safety, and Regulatory Responsibility",
    content: [
      `Laws can regulate talent agencies, model management companies, employment agencies, clients, event producers, employers, and child-performer engagements. A party's legal role depends on its actual conduct, not only the label used in the Platform.`,
      `The party controlling an engagement is responsible for lawful deal terms, pay, overtime, meals, expenses, usage, permits, insurance, workplace safety, harassment policies, supervision, digital-replica authorization, and other client or employer duties that apply.`,
      `Talent should independently verify the Recipient, opportunity, location, compensation, usage, cancellation terms, safety arrangements, and any required license or registration. Report impersonation, coercion, exploitation, trafficking, unsafe conduct, or suspicious payment demands to ${LEGAL_EMAIL}. Immediate danger should be reported to emergency services.`,
    ],
  },
  {
    title: "Copyright, Likeness, Publicity, and Digital Replicas",
    content: [
      `Talent must own or have sufficient license, release, and authority to upload and submit every photograph, recording, and other protected work. The person depicted does not necessarily own the photographer's copyright.`,
      `A submission authorizes evaluation for the stated purpose only. It does not authorize Pholio or a Recipient to use Talent's name, image, likeness, voice, or materials in public advertising, event promotion, press, merchandising, sponsorship, model training, or another commercial use.`,
      `Publicity and commercial use require a separate lawful basis or release describing the approved media, purpose, channels, territory, duration, editing, compensation if any, and withdrawal or termination terms.`,
      `Creation or commercial use of an AI-generated or AI-enhanced digital replica may require separate written approval specifying scope, purpose, duration, and compensation. A general image license or application is not that approval.`,
    ],
  },
  {
    title: "Retention, Withdrawal, and Deletion",
    content: [
      `Active server-side drafts generally expire after 90 days without renewal; a deleted or expired payload can remain recoverable for approximately seven additional days before purge.`,
      `The submitted package is generally scheduled for redaction or deletion approximately 24 months after submission. Status, consent, safety, audit, legal, and limited application records may be kept longer where reasonably necessary or required.`,
      `Talent may withdraw while the application is in a withdrawable state. Withdrawal changes future in-product access and status; it does not undo the historical disclosure, erase all messages or audit records, or recall an independent Recipient copy.`,
      `An erasure request is separate from withdrawal. Send a verified request for Pholio-controlled data to ${PRIVACY_EMAIL} and a separate request to the Recipient for its independent copy. Provider deletion, backups, legal holds, or safety-preservation duties can delay or limit deletion.`,
    ],
  },
  {
    title: "Confirmation Records and Contact",
    content: [
      `Pholio can record the Recipient, opportunity, disclosure version or snapshot, selected package, package fingerprint, submission time, IP address, user agent, Talent confirmation, and linked guardian grant. Those records document the requested transmission; they are not consent to a later contract or secondary use.`,
      `A general Terms acceptance or Privacy Policy acknowledgment is separate from optional AI consent, minor consent, marketing consent, subscription consent, an opportunity submission, publicity rights, and digital-replica authorization.`,
      `Privacy, access, correction, deletion, profiling, or consent questions: ${PRIVACY_EMAIL}`,
      `Recipient, opportunity, safety, payment-demand, or legal questions: ${LEGAL_EMAIL}`,
    ],
  },
];

export function SubmissionProgramNoticeContent() {
  return (
    <LegalDocumentLayout
      title="Talent Submission and Opportunity Notice"
      subtitle="This Notice covers agency-representation submissions and separate casting, event, fashion-week, brand, client, and other opportunity submissions. The Recipient, purpose, terms, data, and selection process can differ by opportunity."
      lastUpdated={LAST_UPDATED}
      effectiveDate={EFFECTIVE_DATE}
      sections={sections}
      contactEmail={PRIVACY_EMAIL}
      footerTitle="Submission or Opportunity Questions"
      footerBody="Do not submit until the Recipient, purpose, eligibility, compensation status, data use, AI use, publicity terms, and withdrawal process are clear."
      companyName={COMPANY_NAME}
      companyAddress={COMPANY_ADDRESS}
    />
  );
}
