import { LegalDocumentLayout, type LegalSection } from "@/components/legal/LegalDocumentLayout";
import { COMPANY_ADDRESS, COMPANY_NAME, EFFECTIVE_DATE, LAST_UPDATED, PRIVACY_EMAIL } from "@/lib/legal-constants";

const sections: LegalSection[] = [
  { title: "Scope and responsibility", content: [
    `This Privacy Policy explains personal information processed in Pholio's websites, application, Public Sites, profiles, applications and related tools (the "Services"). It applies to Talent, Organization personnel, applicants, guardians, people contacting us and visitors, including visitors without accounts. The [Terms](/terms) define Talent, Organization, Recipient, Submission, User Content and Public Site. This prepared version is not effective until publication.`,
    `Pholio determines the purposes and means of processing for its accounts, professional-profile tools, discovery, publication, billing, security and other operations described here. The legal operator and service address will be identified in the effective published version. Privacy requests may be directed to ${PRIVACY_EMAIL}.`,
    `A Recipient generally determines its own application decisions, communications, records and subsequent professional relationships. Its own notice applies to that processing. Where Pholio handles data solely on an Organization's documented instructions, the separate processing terms described below apply. A role depends on the activity, not merely on who uploaded the information.`,
    `This Policy is a notice, not a request for blanket consent. Account acceptance, publication, discovery, a named Submission, optional AI, identity verification, social connections and marketing permissions are distinct choices.`
  ] },
  { title: "Information, sources and purposes", content: [
    `Account and contact information. We receive names, email addresses, sign-in-provider identifiers, role, verification status and account settings from you and the authentication provider. We use these to create and authenticate accounts, manage access, communicate about the service and protect it. Firebase handles credentials; Pholio does not store plaintext passwords.`,
    `Professional profile information. You supply professional names, biographies, location and markets, languages, training, experience, specialties, representation details, social links, work-eligibility or union information and other professional facts. We use them to maintain your dossier, prepare comp cards and packages, display authorized profile information, check stated requirements and support discovery where enabled.`,
    `Age, measurements and appearance information. You may supply birth date, height and other clothing/body measurements, hair and eye color, gender/division, heritage and other appearance information. These can reveal sensitive information or protected characteristics. Birth date supports eligibility and age controls. Other fields support the professional purpose and audience indicated for the field or Submission. We do not treat the mere availability of a field as permission for every audience or secondary use.`,
    `Photographs, documents and media. We receive uploaded images, existing comp cards and other supported material, and links such as event walk videos. We generate thumbnails, formatted images, PDFs, packages, shot labels and technical records. Data can include filenames, format, dimensions, ordering, capture dates you declare, rights metadata and moderation status. We use it for storage, rendering, preparation, publication, requested transmission and safety. Upload a file only if you have the necessary rights; avoid incidental location or third-party information.`,
    `Applications and communications. We receive selected materials, Recipient and event details, notes, availability, status changes, withdrawal requests and messages from Talent and Recipients. We create receipts, package fingerprints, disclosure records and operational audit events. We use them to deliver applications, show what was sent, enable review and communication, administer events and resolve disputes. Private off-Pholio tracker entries and preparation activity are not automatically delivered to the external agency.`,
    `Organization information. We receive agency-access requests, business/contact details, team invitations, roles, permissions, boards, criteria, notes, tags, shortlists, event pick lists and export/webhook settings from Organization personnel. Public sources may supply agency requirements, official links and registration records. We use these for access review, workspace administration, legitimate application handling and accurately sourced reference entries.`,
    `Payment information. Stripe receives payment details directly. Pholio receives customer and subscription identifiers, price/interval, trial and renewal dates, status, invoice/transaction references and relevant billing or tax information for subscription administration, notices, accounting and fraud prevention. We do not store full payment-card numbers or security codes.`,
    `Optional verification and creator information. Stripe Identity may collect identity documents and a matching selfie for an optional adult-verification check. Pholio receives a session reference, result, age/date-of-birth-match outcome, timestamps and error information. Private adult context can include content boundaries and a creator link you supply. Connected-social features may receive account identifiers and provider-returned audience or engagement metrics. See the [Verification Notice](/legal/verification).`,
    `Optional AI and derived information. Depending on the enabled feature and your choices, providers receive selected images, text or limited profile details for technical image classification, writing assistance, photo descriptions or embeddings. Pholio may retain outputs and search-index records. Organization queries may be processed to interpret criteria and order relevant results. These activities and their controls are explained in the [AI Notice](/ai-notice).`,
    `Visitor, technical and usage information. Requests provide IP address, browser/device information, referrer, timestamps and page or action information. Services can record views, shared-link opens, image interactions, contact clicks and approximate market derived from IP. We use information for delivery, security, fraud controls, diagnostics and the analytics described below.`,
    `Permissions, support and safety information. We receive consent/withdrawal actions, Terms acknowledgments, privacy requests, reports and support correspondence, and record relevant versions, timestamps and evidence. We use them to honor choices, investigate concerns, administer rights, enforce rules and meet legal duties. Do not email intimate material or identity documents unless a secure, necessary collection method has been arranged.`
  ] },
  { title: "Publication, discovery and sharing", content: [
    `A Public Site exposes the fields and media selected for public display to visitors, potentially including search engines. Public sites can be copied, downloaded, indexed or cached independently. Social and external links can lead visitors to another service whose privacy practices differ.`,
    `Public publication, agency discovery, a share link and a Submission have separate purposes and controls. Discovery can expose permitted profile information to authorized Organization users without publishing a public page. A Submission delivers the package you authorize to the named Recipient even if your broader profile is private.`,
    `An authorized Recipient may view, download, print or export a Submission and use permitted reviewers. Event workflows may give designated designers access through read-only links without requiring Pholio accounts. The pre-submission notice must identify this additional audience and its purpose. See the [Submission Notice](/legal/submission-program).`,
    `A share link can be forwarded and its opening does not prove who used it. Blocking an Organization limits supported in-product interactions; it cannot prevent that person from seeing already-public material or recalling an independent download. Contact us about a safety-related block or unauthorized disclosure.`,
    `Unpublishing, withdrawing and deleting are different actions. They change the corresponding access in Pholio, subject to processing and caches; they do not erase every prior disclosure, lawful audit record or external copy. Sensitive private adult context is not published merely because you save it or complete verification.`
  ] },
  { title: "Who receives information", content: [
    `We disclose information to the audience you request: public visitors, authorized Organizations, named Recipients and specifically disclosed reviewers. A Recipient independently controls its subsequent decisions and copies. We also disclose information to providers performing the functions described below, subject to the roles and terms applicable to the service.`,
    `[Firebase/Google](https://firebase.google.com/support/privacy) supports authentication; [Stripe](https://stripe.com/privacy) supports billing and optional Identity checks; [Cloudflare](https://www.cloudflare.com/privacypolicy/) supports object storage and delivery; [Neon](https://neon.com/privacy-policy) supports database hosting; and [Netlify](https://www.netlify.com/privacy/) supports hosting and functions. Transactional messages pass through the configured email-delivery provider. Contact us for the provider applicable to your communication.`,
    `[Groq](https://groq.com/privacy-policy/) and [OpenAI](https://openai.com/policies/privacy-policy/) support configured AI activities. Supported alternate semantic-search configurations may use [Voyage AI](https://www.voyageai.com/privacy-policy) or [Cohere](https://cohere.com/privacy); availability and configuration do not mean every provider receives every user's data. The AI feature notice and permission must correspond to the provider actually used.`,
    `[ipapi.co](https://ipapi.co/privacy/) can receive an IP address to return approximate location for market information and geographic controls. Optional social connections can use [Phyllo](https://www.getphyllo.com/privacy-policy) and the connected platform. We do not characterize demonstration metrics as authenticated account facts.`,
    `Providers may act on our instructions for some purposes and independently for purposes described in their own notices, particularly payment, fraud prevention and identity services. These links supplement our explanation; they do not transfer our obligations to you or replace this Policy.`,
    `We may disclose necessary information to professional advisers, auditors, insurers, authorities, courts, NCMEC or other appropriate parties to comply with law or lawful process, report apparent unlawful material, protect people, investigate abuse or establish and defend legal claims. A lawful business transfer may involve relevant records, subject to required protections and notice.`,
    `Pholio does not sell personal information or share it for cross-context behavioral advertising, and does not operate targeted-advertising profiles. We may use aggregate or appropriately de-identified information for service measurement. Information is not anonymous merely because names are omitted; we will not describe linkable visitor or account records as anonymous.`
  ] },
  { title: "Agency data processing", id: "agency-data-processing", content: [
    `Organizations determine the purposes of their applicant evaluations, private notes and subsequent engagements. Where Pholio stores or processes their private workspace records solely on documented instructions, Pholio acts as a processor or service provider for that activity under applicable law and the parties' processing agreement. Our own account, safety, discovery, billing and legal-compliance processing remains separately governed by this Policy.`,
    `The [Agency and Recipient Terms](/legal/agency-terms) require lawful collection, limited access, disclosure of additional reviewers and proper handling of exports and rights requests. They do not imply that every Organization has executed an Article 28 data-processing agreement or approved international-transfer terms.`,
    `For a request about an Organization's decisions, private notes or independent copy, contact that Organization. You may also contact ${PRIVACY_EMAIL}; we will handle data we control and assist or route requests for instructed processing as required. We cannot guarantee deletion from a separate system we do not control.`
  ] },
  { title: "Cookies and visitor analytics", content: [
    `Necessary storage supports sessions, authentication and remembered privacy choices. A shared first-party pholio_consent cookie records the analytics choice across supported pholio.studio subdomains. A persistent portfolio visitor identifier and profile-session cookie are set only when analytics is allowed. You can change or withdraw that choice at [Cookie preferences](/cookies#preferences).`,
    `Some server-side processing continues without those analytics cookies: request/security logs, uncookied view/action counts, shared-link open counts and market/referrer events. An IP address may be sent to the location provider to derive an approximate market, and referrer information may be retained. Consequently, declining analytics cookies does not currently stop all measurement or IP-derived location processing. These records are not necessarily anonymous.`,
    `Talent-facing analytics describe observed activity, such as a page or link being opened; they do not reliably identify the viewer or establish interest, hiring intent or career prospects. A Talent user's analytics setting and the visitor's cookie choice are separate controls.`,
    `The [Cookie Policy](/cookies) gives storage names, purposes and lifetimes. Browser deletion of cookies does not itself delete earlier server records. To request access, deletion or an objection concerning identifiable visitor information, contact ${PRIVACY_EMAIL} with enough context to locate the visit without sending unnecessary sensitive information.`
  ] },
  { title: "Retention and deletion", content: [
    `We retain information for the period reasonably necessary for its stated purpose, considering account activity, the feature's retention period, legal duties, security, disputes and deletion requests. Different records have different purposes; ending public display does not automatically end all lawful retention.`,
    `Account/profile data and media are generally retained while needed for the account and requested features. On a valid deletion request, active records and media are deleted or de-identified subject to lawful exceptions. Provider failures can leave deletion pending. Restricted backups, safety evidence and legal holds may persist beyond removal from active service.`,
    `Application drafts generally expire after 90 days without renewal, with a further recovery period of approximately seven days before payload purge. Representation Submission packages are scheduled for redaction or deletion within 24 months. Event packages use the disclosed event period, normally 90 days after the event ends. A shorter applicable period or lawful deletion request can require earlier action.`,
    `Withdrawal revokes the supported in-product application access and triggers removal/redaction of the package and associated application conversation according to that workflow. Limited status, withdrawal, consent and safety records may remain. Copies already exported to a Recipient are governed by its separate obligations.`,
    `AI descriptions and search derivatives are removed when the relevant consent is withdrawn or the source data is deleted, subject to completion of the relevant deletion processes. Search query/cache records have separate operational retention. Provider-held information follows the applicable service configuration and legal requirements; do not assume deletion of a local output erases a provider's records.`,
    `For Identity checks, Pholio retains limited verification/audit results and requests provider redaction after processing completed verification results. Redaction is a provider operation and may remain incomplete after a failure. The [Verification Notice](/legal/verification) explains the separate handling of ID/selfie information and review requests.`,
    `Visitor cookies last for the periods in the Cookie Policy; those periods are not server-data retention periods. Analytics, logs, messages, support and rights records are retained according to their purpose and applicable legal obligations. We do not promise a universal 90-day purge of these records. Contact us for the applicable period or deletion request.`,
    `Billing, tax, consent, complaint and dispute records may be retained to meet accounting, legal or evidentiary duties. Account deletion does not currently cancel a Stripe subscription or by itself erase all payment, Identity or connected-social provider records. Cancel through billing and contact us for any additional provider-related request.`
  ] },
  { title: "Your choices and privacy rights", content: [
    `You can edit profile information, use available audience controls, withdraw supported Submissions, change optional AI settings, disconnect supported integrations, export account data and request account deletion. You may also contact ${PRIVACY_EMAIL}. Use a separate, specific choice for publicity or digital-replica permission; account acceptance does not grant it.`,
    `Depending on the law applicable to you and to Pholio, you may request confirmation of processing, access and information about categories/sources/purposes/recipients, correction, deletion, a portable copy, restriction, objection, withdrawal of consent, or human review of qualifying automated decisions. You may have rights to opt out of sales, targeted advertising or certain profiling and to limit qualifying sensitive-information uses. We do not require payment or a Studio+ subscription to exercise statutory rights.`,
    `For a request, explain what you seek and provide the account email or other information reasonably needed to locate the data. We will verify identity and authority proportionately, accept authorized-agent requests where law requires, and avoid requesting unnecessary sensitive evidence. We will explain a lawful refusal or limitation and respond within the applicable statutory period, including any permitted extension with notice.`,
    `If we refuse a request and applicable law provides an appeal, reply to our decision or email ${PRIVACY_EMAIL} with "Privacy appeal" and the request reference. We will review it and explain the outcome and available regulator-complaint route within the legally required period. You may complain to your state attorney general or other competent privacy authority. We will not unlawfully discriminate or retaliate for exercising rights.`,
    `For California residents, the collection, purpose, recipient and retention sections above describe the categories handled by this service, including identifiers, commercial information, internet activity, professional information, visual information and potentially sensitive information. CCPA rights and disclosures apply when its coverage conditions are met; this Policy does not assert that Pholio meets a revenue or volume threshold. California residents may request information about qualifying direct-marketing disclosures under Civil Code section 1798.83; Pholio does not disclose personal information to others for their own direct marketing.`,
    `Where a legally recognized universal opt-out signal applies to an activity, it must be honored for that activity. Because Pholio does not sell information or use targeted advertising, there is no such sale/advertising activity to opt out of. Browser signals do not substitute for every feature-specific consent or delete historical information.`
  ] },
  { title: "Young people and sensitive information", content: [
    `The launch talent service is for adults. We do not invite children under 13 to use it or knowingly authorize new minor accounts. If we learn that information about an under-13 child was collected, we will restrict the activity and address deletion or any legally required preservation. Report it to ${PRIVACY_EMAIL}; no account is required.`,
    `The intended later guardian program is subject to separate eligibility, age assurance, authorization and child/teen privacy controls. A guardian's account authority does not automatically authorize a named disclosure, nonessential teen processing, publicity or work. See the [Guardian and Young Talent Notice](/legal/guardians). Existing minors and authorized guardians retain applicable privacy and safety rights while account activity is restricted.`,
    `Do not put identity documents, precise home addresses, health records or intimate imagery into ordinary profile fields. Identity verification has a dedicated provider workflow. A private adult-context preference is not consent to an engagement or a release. Photographs and measurements can be sensitive even when a particular statute does not classify every photograph as biometric data.`
  ] },
  { title: "International processing and legal grounds", content: [
    `The initial talent offering is United States-focused. Providers may process information in the United States and other locations where they operate; local protections can differ. Preparing a package for an agency abroad does not itself change where a Pholio account is offered. Sending that package can result in an international disclosure to the Recipient you select.`,
    `When European or UK data-protection law applies to an activity, processing necessary to supply a requested service may rely on contract; proportionate account security, abuse prevention and administration may rely on legitimate interests; legally mandated records and disclosures rely on legal obligation; and optional processing requiring permission relies on consent. Emergency protection may rely on vital interests where legally available. We must separately establish a lawful condition before processing special-category information; an ordinary service contract is not that condition.`,
    `You may have rights to object to legitimate-interest processing, withdraw consent prospectively, restrict processing and complain to your local supervisory authority. These rights are not conditioned on our describing the launch as US-focused. Where restricted international transfers occur, Pholio must use a legally valid mechanism applicable to those transfers. This Policy does not claim an unverified certification or executed transfer clauses.`,
    `Intentional expansion into additional countries requires corresponding notices, representative details where required, contracts and controls. A foreign Public Site visitor is still covered by this Policy and any law that actually applies.`
  ] },
  { title: "Security and changes", content: [
    `We use access controls, authenticated sessions, encrypted transport and managed infrastructure to protect information. No system guarantees perfect confidentiality or availability. Public content is intentionally accessible; report unauthorized private access, suspected compromise or a privacy incident promptly to ${PRIVACY_EMAIL}. We provide breach notifications when and within the periods required by law.`,
    `Last Updated records text revision; Effective Date records when a published notice becomes operative. We will explain material changes and provide required notice or obtain a new specific consent before materially different processing that requires it. A new notice cannot retroactively authorize earlier processing. Request an earlier version at ${PRIVACY_EMAIL}.`
  ] }
];

export function PrivacyContent() {
  return <LegalDocumentLayout title="Privacy Policy" subtitle="How Pholio handles account, portfolio, application, visitor and optional-feature information, and how to exercise your choices and rights." lastUpdated={LAST_UPDATED} effectiveDate={EFFECTIVE_DATE} sections={sections} contactEmail={PRIVACY_EMAIL} footerTitle="Privacy requests and questions" companyName={COMPANY_NAME} companyAddress={COMPANY_ADDRESS} />;
}
