import { LegalDocumentLayout, type LegalSection } from "@/components/legal/LegalDocumentLayout";
import { COMPANY_ADDRESS, COMPANY_NAME, EFFECTIVE_DATE, LAST_UPDATED, LEGAL_EMAIL } from "@/lib/legal-constants";

const sections: LegalSection[] = [
  { title: "The agreement and the Services", content: [
    `These Terms of Service ("Terms") govern Pholio's public website, application, hosted talent websites and related tools (the "Services"). "Pholio," "we," "us" and "our" refer to the operator identified in the published version of these Terms. This version is prepared for publication and is not yet effective.`,
    `"Talent" is an individual whose professional profile or materials are maintained or submitted through the Services. An "Organization" is an agency, model management company, casting organization, event organizer, brand, client or other organization using a workspace. A "Recipient" is the identified Organization or other person receiving materials for a stated purpose. A "Submission" is a package Talent authorizes Pholio to deliver to a named Recipient. "User Content" includes profiles, photographs, other supported media, text, messages and records a user provides. A "Public Site" is a portfolio or website Talent publishes through the Services, including a connected custom domain where supported.`,
    `When these Terms are effective, you accept them by an affirmative acceptance action presented with a link to them. If you act for an Organization, you must have authority to bind it; the Organization is responsible for its authorized users. You may not use an account if you decline its applicable agreement. Receiving a portfolio link does not constitute acceptance of account or subscription terms.`,
    `The [Community Guidelines](/community-guidelines) apply to the Services. The [Submission Notice](/legal/submission-program), [Subscription Terms](/legal/subscriptions) and [Agency and Recipient Terms](/legal/agency-terms) form part of this agreement when you use the corresponding features. Their specific provisions control for their subject matter. A signed agreement controls a conflict only to the extent it expressly addresses it. Opportunity terms govern the relationship with that Recipient and cannot expand Pholio's content rights or authorize undisclosed sharing.`,
    `The [Privacy Policy](/privacy), [Cookie Policy](/cookies), [AI Notice](/ai-notice) and [Verification Notice](/legal/verification) explain data handling. Acknowledging a notice is not consent to optional processing, publicity, biometric processing or an unrelated Recipient's use. Those permissions must be obtained separately where required.`
  ] },
  { title: "Eligibility and accounts", content: [
    `The initial talent service is for adults aged 18 or older in the United States. Features, opportunities and paid plans may have narrower geographic restrictions. A reference to an agency abroad does not make accounts or paid services available there. Organization users must be adults authorized to act for their Organization.`,
    `Minors may not open or operate new talent accounts during the adults-only launch, even with guardian permission. The [Guardian and Young Talent Notice](/legal/guardians) covers existing minor-data requests and conditions for a later, expressly enabled program. It does not open that program. Do not provide information about a child under 13 or bypass an age restriction.`,
    `Provide accurate information, keep contact details current, protect your credentials and use individual Organization seats rather than sharing passwords. You are responsible for authorized activity and must promptly report suspected compromise to ${LEGAL_EMAIL}. You are not automatically responsible for activity caused by our failure to meet duties imposed by law.`,
    `We may request information reasonably necessary to confirm eligibility, authority or security and restrict an account while a material concern is investigated. A declared birth date, identity check, agency listing or registry record is a limited check, not a guarantee of safety, professional qualification or lawful eligibility for work.`
  ] },
  { title: "Scope of the service", content: [
    `Pholio provides professional profiles, digitals and media organization, comp cards, application preparation and tracking, Public Sites, optional analytics, and tools for Organizations to receive and review materials. Workflows can include requirements checks, file conversion and exports, receipts, messages, material requests, comparison, shortlists, event casting and handoff to Recipient systems. These terms govern a feature when offered; they do not promise that every feature is available at launch, in every location or on every plan.`,
    `Pholio does not undertake to represent Talent, procure employment, negotiate compensation, enter representation or booking agreements on Talent's behalf, collect Talent's earnings or charge a commission on engagements. Representation, employment, contractor and event relationships require separate arrangements between the relevant parties. A label or disclaimer cannot displace a legal duty arising from our actual conduct.`,
    `Agency tools support intake, evaluation, communication, decisions and handoff. A status such as shortlisted, offered, accepted, confirmed or represented records a workflow event; it does not itself supply a representation agreement, employment contract, release, work permit or proof of payment.`,
    `Studio+ does not buy greater application reach, preferential agency presentation, search placement, review speed, selection odds, representation or work. Open-call applications are free. Discovery anti-spam limits apply equally across paid and free plans. See the [Subscription Terms](/legal/subscriptions).`
  ] },
  { title: "Market and external applications", content: [
    `Market can include participating Organizations and reference entries for agencies outside Pholio. A reference entry, requirements summary, logo, registry citation or external link does not imply partnership, endorsement or receipt of applications through Pholio. The displayed destination and method determine the available route.`,
    `Preparing a package, ZIP file, comp card or email draft for an off-Pholio route does not send it. You complete delivery through the recipient's own form, email or other channel. An entry you mark sent in your tracker is your record, not proof of delivery, opening, review or a decision. External services have their own terms and privacy practices.`,
    `Requirements and registration information can change. A source or checked-on date describes the record consulted, not continuing compliance. Completeness, freshness and format checks evaluate supplied information against stated criteria; they do not establish professional potential, image authenticity or why a Recipient declined you.`,
    `A timed closure or no-response label indicates that a stated review period elapsed. Unless a Recipient recorded a decision, it does not mean the Recipient reviewed or rejected the application. Profile refreshes ordinarily affect future packages and do not silently rewrite Submission receipts. The [Submission Notice](/legal/submission-program) explains these distinctions.`
  ] },
  { title: "Content ownership and operational license", content: [
    `You retain the rights you hold in User Content. Being depicted in a photograph does not necessarily make you its copyright owner. You must hold the licenses, permissions and authority necessary for each upload, publication or transmission you request, including copyright, privacy and publicity rights.`,
    `You grant Pholio a nonexclusive, worldwide, royalty-free license to host, store, reproduce, resize, convert, format, display and transmit User Content to provide requested features, maintain security, address abuse and comply with law. We may authorize service providers to perform these operations on our behalf under appropriate restrictions. The license is limited by the audience and purpose of the feature and does not transfer ownership.`,
    `For a Submission, you authorize the named Recipient and its permitted reviewers to use the package for the purpose disclosed before submission and related administration. Downloads and exports remain subject to Recipient obligations and applicable law. Public viewers may view published content; publication does not grant a general commercial reuse license.`,
    `This operational license does not independently authorize advertising with your likeness, merchandising, training general-purpose AI models on your content, or creation or commercial use of a digital replica. Marketing and likeness uses require separate permission describing the proposed use. A rights ledger records permission; it cannot confer copyright or authority the granting person does not possess.`,
    `The license ends when the corresponding content is deleted from our active systems, except as necessary to complete requested transmission, maintain permitted historical records, comply with law or legal holds, resolve disputes, and manage restricted backups and provider deletion cycles. The [Privacy Policy](/privacy) explains retention. We cannot recall copies retained outside our control.`
  ] },
  { title: "Public Sites and domains", content: [
    `You decide whether to publish a Public Site and are responsible for its content and links. Review publication and audience controls. Public publication, Organization discovery, a share link and a Submission are distinct disclosures. Making one private does not automatically revoke the others.`,
    `Public information may be indexed, copied or shared, and a reviewer may forward a link. Use available unpublish and link-revocation controls and report unauthorized access promptly. Removing a page does not guarantee immediate removal from independent caches or third-party copies.`,
    `Where custom domains are supported, you must own or be authorized to connect the domain and maintain its registration and DNS settings. Connecting a domain does not transfer it to Pholio or make us your registrar. Registration, renewal fees and third-party terms remain your responsibility unless a separate order expressly states otherwise.`,
    `Do not use a Public Site to impersonate someone, offer unlawful services or publish prohibited material. Do not add unauthorized trackers, collect visitor information without required notices, or imply Pholio or agency endorsement. We may restrict a domain, link or publication to address rights, security or safety. Export important materials before closing an account or losing a paid publishing feature.`
  ] },
  { title: "Agency workspace use", id: "agency-workspace-use", content: [
    `Organizations must comply with the [Agency and Recipient Terms](/legal/agency-terms). Access is limited to personnel and reviewers with a legitimate role in the purpose disclosed to Talent. Keep permissions current, safeguard exports, webhooks and bearer links, and end access when a person's role ends.`,
    `Do not use a workspace to obtain unrelated mailing lists, scraped dossiers or unrestricted media. Do not sell Talent information, share it with undisclosed clients, train models on it or obtain publicity/digital-replica rights through general application acceptance. Other purposes require a separate agreement and lawful permission.`,
    `Each Recipient is responsible for its decisions, required notices, independent copies and lawful dealings with Talent. An Organization cannot promise on Pholio's behalf that a person will be represented, booked or paid.`
  ] },
  { title: "Agency fair decision-making", id: "agency-fair-decision-making", content: [
    `Recipients must apply lawful criteria relevant to their stated purpose and must not unlawfully discriminate, harass or retaliate. A physical or demographic field does not establish that a criterion is lawful for every opportunity. Provide required accommodations and alternative application routes.`,
    `Search, filters, technical checks and optional semantic ordering assist review; they do not establish suitability or dictate a decision. Recipients must exercise meaningful human judgment and meet applicable automated-decision, employment and civil-rights requirements. A human final decision does not by itself remove a tool from those laws.`,
    `The [AI Notice](/ai-notice) explains Pholio tools. Recipient-side notices, audits and explanations must describe the particular use. Accepting these Terms does not waive applicant rights or replace those obligations.`
  ] },
  { title: "Messaging, safety and engagements", content: [
    `Use messages, reply links and material requests for their legitimate application or professional purpose. Messages are not end-to-end encrypted. Pholio and its providers may process them for delivery, support, security, lawful requests and abuse investigation as described in the Privacy Policy.`,
    `Do not send scams, coercive demands, harassment, threats, sexual solicitations, malware or requests to bypass age, consent or safety restrictions. A photograph or stated content boundary is not consent to a shoot, sexual activity, nudity, travel, medical examination or publication.`,
    `Before an engagement, the relevant parties must settle compensation, expenses, image uses, cancellation and safety in an appropriate separate agreement. The party responsible for a workplace or engagement retains its labor, licensing, insurance and safety duties.`,
    `Report concerns under the [Community Guidelines](/community-guidelines). Use the [intimate-image removal procedure](/take-it-down) for nonconsensual intimate images and the [copyright procedure](/dmca) for infringement. Reporting does not require an account. Contact emergency services if someone is in immediate danger.`
  ] },
  { title: "Service integrity and third parties", content: [
    `You may use the Services for your professional purposes or your Organization's authorized activities. Pholio and its licensors retain rights in software, designs, trademarks and material they supply. Do not resell the Services, misappropriate branding, scrape profiles, circumvent access controls, deploy harmful code or access another user's account. Restrictions on reverse engineering do not apply where law gives a nonwaivable right.`,
    `We may use voluntarily offered suggestions to improve the Services without compensation. This does not grant rights to private messages, unpublished portfolios or third-party material included with feedback.`,
    `Third-party payment, identity, social, hosting and AI services have distinct roles. Their terms may apply when you choose their service. We retain obligations the law assigns to us; using a provider does not transfer those duties.`
  ] },
  { title: "Restriction and account closure", content: [
    `You may stop using the Services and request deletion through account settings or the Privacy Policy contact. Cancel an active subscription through billing before deleting your account; deletion is not presently a subscription-cancellation instruction. Contact ${LEGAL_EMAIL} if billing is inaccessible or a charge continues.`,
    `We may restrict access, remove content or suspend or terminate an account for material breach, credible safety or security concerns, fraud, unlawful use or a legal requirement. Where appropriate and legally permitted, we will explain the action and allow a response or correction. Urgent protection may precede notice. Request review at ${LEGAL_EMAIL}.`,
    `We may change or discontinue features. If we discontinue a material paid service without your breach, we will give reasonable notice where practicable and an appropriate refund for the unused prepaid period, subject to stronger legal rights.`,
    `Closure does not extinguish accrued rights, lawful charges, records retained under lawful exceptions, or obligations that by their nature survive, including content-use restrictions, confidentiality and dispute provisions. Privacy and safety requests remain available after closure.`
  ] },
  { title: "Service limitations and liability", content: [
    `We will perform our obligations with the care required by law. We do not guarantee uninterrupted availability, error-free checks, Recipient responses or professional outcomes. Keep copies of important materials and assess Recipient terms before relying on them.`,
    `TO THE EXTENT PERMITTED BY LAW, THE SERVICES ARE PROVIDED AS AVAILABLE, WITHOUT IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. NOTHING EXCLUDES NONWAIVABLE CONSUMER GUARANTEES OR LIABILITY THAT CANNOT LAWFULLY BE EXCLUDED.`,
    `To the extent permitted by law, neither party is liable to the other for indirect or consequential loss that was not reasonably foreseeable when contracting. Pholio's aggregate liability arising from the Services is limited to the greater of US$100 or the fees you paid Pholio in the twelve months before the event giving rise to the claim.`,
    `These limits do not apply to fraud, intentional misconduct, gross negligence, death or personal injury caused by negligence, or other liability that law does not permit us to exclude or limit. They do not limit statutory privacy, labor, intellectual-property or consumer remedies where contractual limitation is prohibited.`,
    `An Organization must indemnify Pholio against third-party claims and reasonable defense costs caused by its unlawful Talent-data use, infringement through material it supplies, or material breach of Recipient obligations, except to the extent caused by Pholio's breach or misconduct. Pholio must promptly notify it, reasonably cooperate and permit an appropriate defense. A settlement may not impose admissions or nonmonetary duties on another party without consent. This indemnity does not apply to individual Talent consumers using their own accounts.`
  ] },
  { title: "Disputes and general provisions", content: [
    `Contact ${LEGAL_EMAIL} with the issue and resolution sought so we can attempt to resolve a dispute. This is not a mandatory waiting period for urgent relief, regulatory complaints or statutory deadlines. These Terms do not require arbitration or waive class proceedings or jury-trial rights. Applicable law determines governing law and competent courts, including mandatory protections where you reside.`,
    `Neither party may transfer this agreement in a way that reduces the other's mandatory rights. Pholio may transfer it with the Services in a lawful corporate transaction, subject to required notice and privacy protections. If a provision is unenforceable, the rest continues to the extent the agreement can lawfully operate. Delay in enforcement is not waiver.`,
    `These Terms and applicable incorporated documents are the agreement for the Services. They do not replace a separately signed representation, employment, event or data-processing agreement. Electronic notices may be delivered through your account or contact details, with additional delivery requirements observed where law requires.`
  ] },
  { title: "Versions and effective dates", content: [
    `"Last Updated" is when the text was most recently revised. "Effective Date" is when a published version becomes operative. The dates need not coincide. A draft marked publication pending does not replace an operative agreement.`,
    `On first publication, these Terms apply to new users upon affirmative acceptance of the effective version. For later material changes, we will give notice of the changes and operative date and obtain renewed acceptance where required. We will not retroactively expand a content license or manufacture consent to earlier processing.`,
    `If you decline a revision requiring acceptance, you may stop using the affected service and close your account while retaining applicable export, privacy and safety rights. Request an earlier version at ${LEGAL_EMAIL}.`
  ] }
];

export function TermsContent() {
  return <LegalDocumentLayout title="Terms of Service" subtitle="The agreement governing Pholio accounts, professional materials, public websites, applications and Organization use." lastUpdated={LAST_UPDATED} effectiveDate={EFFECTIVE_DATE} sections={sections} contactEmail={LEGAL_EMAIL} footerTitle="Legal questions" companyName={COMPANY_NAME} companyAddress={COMPANY_ADDRESS} />;
}
